### ISSUE TITLE
How to access the "Last heard from" field?

### ISSUE THREAD

**Issue by nvivo** [intercom/intercom-dotnet#128]
There is a field in Intercom called "Last heard from":

![image](https://user-images.githubusercontent.com/202449/41309407-1ceff65e-6e55-11e8-8044-9b42b4070f06.png)

Can this field be accessed from this API? I'm not finding it anywhere.

**Comment by kmossco** [comment]
Hey @nvivo! This attribute is not something we expose in our API requests, but internally it is derived from a timestamp for the last time the user has contacted you - as in, initiated a conversation. Unfortunately because this isn't in the API User Model, then we can't add it to the SDK either. But I'll add this as a feature request for our API team! 😉

**Comment by mindojo-victor** [comment]
Any news on adding this field to the API?

**Comment by vquinn16** [comment]
Hello - Do you have an update as to when/if you will be adding this field to the API?
