### ISSUE TITLE
Environment.GetEnvironmentVariable

### ISSUE THREAD

**Issue by kfrancis** [intercom/intercom-dotnet#5]
Can I suggest that this isn't a great way to get the two secure variables? It's kind of ugly to ask people to put those credentials on their computer just to run tests. I realize they aren't really in use, but it sticks out as a weird choice.

The method used in Intercom.Tests seems more normal.

**Comment by khalilovcmd** [comment]
Thank you @kfrancis for dropping by your suggestions! 

Please bear with me with a bit of explaining our philosophy behind this. Our Unit tests were primarily targeted towards the functionality of each of the public clients' functionality without having to do an API endpoint, thus we didn't require an AppId or an AppKey.

Our purpose through the yet-to-be-written integration tests is to solely test the API Endpoint as a whole rather than as a unit to allow us to have more trust in the way we make requests and handle responses. (one could definitely argue that mocking is a standard practise, yet, we feel an API Endpoint test is important in our case)

**E.g.:** Creating a user, removing a company from a user, creating an event with metada, etc.

And for that, we explicitly ignore the integration tests here:

```csharp
Assert.Ignore("Intercom.Integration.Tests will be ignored because there are no environment variables defined for IntercomAppKey or IntercomAppId.");
```

So in all cases, you can run the unit tests, and if you feel that you would like to try and run your integration tests, you could do that or by default it will be ignored.
