### ISSUE TITLE
Get all conversations

### ISSUE THREAD

**Issue by sofiaChat** [intercom/intercom-dotnet#69]
Hello!
Is there a way to get a list of all conversations? Is the only way to get all converstaions through users and admins?

Thanks in advance

**Comment by choran** [comment]
Hi @sofiaChat 
Yeah, this is correct, you need to list either via admin or user.
Out API does allow you to list [all conversations](https://developers.intercom.com/reference#list-conversations) so we should also have that in the SDK
I was unaware we did not allow this but it seems like you are right.
This is something we would want to address. If anyone wanted to submit a quick PR for the we would happily review, we are trying to get to all our PRs asap now.
But either way it is something we should get to ourselves at some point since it is a reasonable request
Thanks
Cathal

**Comment by dereckbester** [comment]
+1 For this request
