### ISSUE TITLE
WHO does this

### ISSUE THREAD

**Issue by ditchcode** [intercom/intercom-dotnet#96]
I cannot believe after all this time the output library is still named Library.dll.  What decent development team would make a decision to do this with the intention of releasing their API to the community?

**Comment by kmossco** [comment]
Hey @ditchcode! Completely understandable that it isn't the best of names, and it's actually something I hope to have fixed with a PR coming this week, so thank you for your feedback on this. 

Note however that we are always happy to get Pull Requests from the community, so if you spot something that isn't quite right and have the time, feel free to send us a PR to review. We'll be happy to have more people contributing to this library. 👍

**Comment by kmossco** [comment]
I have now pushed a PR to fix this problem. Feel free to give it a shot and see if this fixes what you were referring to with the library output. I'll only close this when the PR is merged successfully. 👍

**Comment by kmossco** [comment]
This is now fixed in the new version. 🎉
